### PR TITLE
⚙️ Refactor API HTTP server to use PostgreSQL database as data backend 

### LINKED ISSUE #21: Refactor API HTTP server to use PostgreSQL database as data backend
Refactor API HTTP server code to build a PostgreSQL database and load data from the database to handle HTTP requests.

The PostgreSQL database will be available through Amazon Relational Database Service (RDS). Code and documentations will be in another GitHub repository.

Use R odbc package <https://db.rstudio.com/r-packages/odbc/> to build the PostgreSQL database.

Refactor R functions in `src` directory to use R odbc package to load data from the PostgreSQL database.

cc @taylordm @chinwallaa @blackdenc

### LINKED ISSUE #22: TPM plot linear scaling compresses GTEX plots for genes with high expression in cancer groups vs GTEX
TPM plots linear scaling works well for BRAF in Nb vs GTEX
https://openpedcan-api-qa.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621

ALK in Nb has~25x greater expression vs BRAF and this expands the y-axis so that the GTEX sample cohorts’ boxes are compressed and don’t show a difference between sample types.
https://openpedcan-api-qa.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&efoId=EFO_0000621
shows that

### LINKED ISSUE #23: Extreme TPM outliers extend y-axis upper limit too much
As pointed out by @dunnpa in [a slack message]( https://opentargetspediatrics.slack.com/archives/C021Z53SK98/p1630595690037300?thread_ts=1630528313.036600&cid=C021Z53SK98),

> It was not hard to find an example that highlights the limits of the linear scaling.
>
> ALK in Nb has~25x greater expression vs BRAF and this expands the y-axis so that the GTEX sample cohorts’ boxes are compressed and don’t show a difference between sample types.
>
> image

Following are potential solutions:

- Keep linear scale. Discard extreme outliers from the plot, by setting y-axis upper limit to 10 * median, only if there is any extreme outlier, say max / median > 100.
- Use log scaled y-axis if there is any extreme outlier, say max / median > 100.

This issue will only be worked on after #21 is resolved.

cc @jharenza @komalsrathi @taylordm @chinwallaa @jonkiky

### PR DESCRIPTION
**Pull request by logstar**
# Pull Request Template

## Description

Refactored `OpenPedCan-api` HTTP server to use PostgreSQL database as data backend. The database is hosted on an Amazon RDS (relational database service) instance that is not publicly available.

(EDIT 09/16/2021 YZ: Changes for resolving #22 and #23 are added to this PR. The changes are not submitted as a standalone PR, mainly because the DEV host can only deploy the latest commit. Submitting a standalone PR will make the DEV server out of sync with this PR, which would be confusing to the reviewers.)

- Resolved #21
- Resolved #22 
- Resolved #23 

## Type of change

- [x] Refactor (non-breaking change which does not change any interfaces)
- [x] This change requires a documentation update

### Changed

- Changed required parameters in `/tpm/gene-disease-gtex/plot` and `/tpm/gene-all-cancer/plot` endpoints, by adding `yAxisScale` as a required parameter.
- Changed `tests/curl_test_endpoints.sh` to test `yAxisScale` parameter.
- Changed data model layer backend from memory to database.
- Changed data model building procedure in `db/build_db.sh`.
- Changed data model loading procedure in `db/load_db.sh`.
- Changed `.dockerignore` to ignore `OpenPedCan-analysis` and `db/build_outputs`. The ignored directories are bind mounted to docker containers when necessary, in order to prevent transferring a large amount, potentially over 100GB, of data to docker daemon when building images.
- Changed static code analysis script from `tests/run_r_lintr.sh` to `tests/run_linters.sh`.

### Added

- Added `yAxisScale` as a required parameter in `/tpm/gene-disease-gtex/plot` and `/tpm/gene-all-cancer/plot` endpoints.
- Added `docker-compose.yml` to test coordinations between `OpenPedCan-api` HTTP server and database server locally.
- Added `db/db.Dockerfile` to test run `OpenPedCan-api` database server locally.
- Added `db/build_tools` to organize tools for building data model.
- Added `db/build_outputs` to organize output files of data model building procedure.
- Added `db/init_db.sh` and `db/init_db_pwfile.sh` to initialize database management system (DBMS) for building and loading data model locally.
- Added `db/r_interfaces` for analysis logic layer to interact with data model layer.
- Added `.env` file for `docker-compose.yml` runtime environment.
- Added `tests/linters` to organize static code analysis tools.
- Added `tests/git_diff_image.sh` to compare images with git `HEAD` for pixel differences.
- Added `/db-stats` API testing endpoint to get database statistics.
- Added `/db-connection` API testing endpoint to run a simple query.

## How Has This Been Tested?

- [x] Integration test in local and dev environments.

<details>
  <summary>**Terminal returns for testing dev environment. Click to expand.**</summary>

```text
$ git st
On branch logstar/database
Your branch is up to date with 'origin/logstar/database'.

nothing to commit, working tree clean
$ rm tests/http_response_output_files/png/*.png tests/http_response_output_files/json/*.json tests/results/*.tsv

$ API_HOST=dev ./tests/curl_test_endpoints.sh

...

GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.659019 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.054161 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.098527 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.607373 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.600237 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.066156 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.623877 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.050345 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.095424 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.569421 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.872360 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.132324 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.582242 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.212843 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.034737 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000213420
http_code: 200
content_type: application/json
time_total: 0.545608 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.502678 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.278824 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.676566 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.702462 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.025284 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.566825 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.728143 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.049902 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.547638 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.078713 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.700286 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.630347 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.732774 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.031826 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.554350 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.077286 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.705899 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000157764
http_code: 200
content_type: application/json
time_total: 0.600702 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.520411 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.273849 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.829585 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.903560 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.918786 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.831734 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.728039 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.765546 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.825351 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.789936 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.228295 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.725222 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.203134 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.996922 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.720915 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.859512 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.265496 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
http_code: 200
content_type: application/json
time_total: 0.701966 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.406920 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.774719 seconds

# test/ plots and tables are reproduced identically.
$ git st
On branch logstar/database
Your branch is up to date with 'origin/logstar/database'.

nothing to commit, working tree clean
```

</details>

For more details about local testing environment, options, and resources, see <https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/edfa89c5bd82d6d6b8b8ea901e6947f82d70f5d2/README.md#3-test-run-openpedcan-api-server-locally>.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
- [NA] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have emojis in my PR and commits 😉

cc @taylordm @chinwallaa @jonkiky @dunnpa @jharenza @afarrel

### CODE REVIEW

**Comment by logstar** [comment]
> @logstar since you are adding a bunch of linters in this PR, can you also check if they're already run in the current Github actions checks, and add them to the workflow [here](https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/logstar/database/.github/workflows/linter.yml)? I'm happy to help out with that if necessary.

@blackdenc Thank you for checking. The added linters, including hadolint and shellcheck, are already in the GitHub action checks. Added them for quick local checking.

**Review by chris-s-friedman — APPROVED** [review]
Looks great - exciting to see all the changes and improvements!

since plumber.R is starting to get a bit long - have you considered breaking that file out into multiple files, sourced in plumber.R - e.g. https://github.com/rstudio/plumber/issues/266

**Comment by logstar** [comment]
> Looks great - exciting to see all the changes and improvements!

Thank you for the review @chris-s-friedman . I will merge this PR soon.

> since plumber.R is starting to get a bit long - have you considered breaking that file out into multiple files, sourced in plumber.R - e.g. [rstudio/plumber#266](https://github.com/rstudio/plumber/issues/266)

Thank you for the suggestion. Currently, `plumber.R` has the following numbers of lines:

- Blank lines: 53. Help reader to separate code constructs.
- Comments: 120. Documentation. Explain code.
- Code: ~100. Simple function calls, without any complex processing.

I have considered breaking `plumber.R` into multiple files, but line number is not one of my concerns. My main concerns are unit testing, environment management, and namespace separation. 

Before starting to split `plumber.R` into multiple files, I need to look further into the documentation and source code how R plumbr manages environment and namespace. Do you have any pointers on them? The GitHub issue [rstudio/plumber#266](https://github.com/rstudio/plumber/issues/266) seems to have no discussion on them.

**Comment by kelseykeith** [comment]
### Code and Results Review

Everything looks good! No real errors that I can find

- Code is pulling from the correct version of the data.
- Plot has the correct axis, either linear or log10, based on the scale requested
- Results from the API call match data in OpenPedCan-analysis tables.

One last thing that was unexpected, but not exactly a problem, but odd enough that I wanted to mention it. The plots for "EFO_0003094", Ganglioglioma, were supposed to fail because that cancer group only has 2 RNA-seq samples and only groups with 3 or more samples return results on MTP. However, instead of failing as it did in previous versions of the API, it returned a JSON or a PNG that was really a text file with the error message in it `{"error":"500 - Internal server error"}` which was unexpected in the case of the PNG.

**Comment by logstar** [comment]
> ### Code and Results Review
> Everything looks good! No real errors that I can find
> 
> * Code is pulling from the correct version of the data.
> * Plot has the correct axis, either linear or log10, based on the scale requested
> * Results from the API call match data in OpenPedCan-analysis tables.
> 
> One last thing that was unexpected, but not exactly a problem, but odd enough that I wanted to mention it. The plots for "EFO_0003094", Ganglioglioma, were supposed to fail because that cancer group only has 2 RNA-seq samples and only groups with 3 or more samples return results on MTP. However, instead of failing as it did in previous versions of the API, it returned a JSON or a PNG that was really a text file with the error message in it `{"error":"500 - Internal server error"}` which was unexpected in the case of the PNG.

@kelseykeith - Thank you for reviewing.

We can discuss further about the error message. I think failing requests are always responded with [HTTP  500 status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors), which should be considered as an error by any API caller. HTTP status code 500 is probably also the default failing status code of R plumber, and there is an issue to make the error responses more informative, <https://github.com/PediatricOpenTargets/OpenPedCan-api/issues/33>. The error message `{"error":"500 - Internal server error"}` is in the body of the HTTP response, which is the default error message of R plumber.

**Pull request merged**
