### PR TITLE
🖼 Change `tpm/gene-disease-gtex` boxplot title

### LINKED ISSUE #40: Change `gene-disease-gtex` boxplot title
Change `gene-disease-gtex` boxplot title from "Primary tumor vs GTEx tissue bulk gene expression" to "Primary tumor and GTEx tissue bulk gene expression", as suggested by @taylordm .

Changing "vs" to "and" to clarify that the boxplot does not imply any differential expression.

### PR DESCRIPTION
**Pull request by logstar**
# Pull Request Template

## Description

Changed `tpm/gene-disease-gtex/plot` boxplot title from "Primary tumor vs GTEx tissue bulk gene expression" to "Primary tumor and GTEx tissue bulk gene expression", as suggested by @taylordm .

Changed "vs" to "and" to clarify that the boxplot does not imply any differential expression.

Resolves #40 .

## Type of change

Non-breaking change.

### Changed

- Changed `tpm/gene-disease-gtex/plot` boxplot title from "Primary tumor vs GTEx tissue bulk gene expression" to "Primary tumor and GTEx tissue bulk gene expression".

## How Has This Been Tested?

- [x] Integration test

<details>
  <summary>**Terminal returns for testing DEV host. Click to expand.**</summary>

```text
$ git st
On branch logstar/boxplot-title
Your branch is up to date with 'origin/logstar/boxplot-title'.

nothing to commit, working tree clean

$ rm tests/http_response_output_files/png/*.png tests/http_response_output_files/json/*.json tests/results/*.tsv

$ API_HOST=dev ./tests/curl_test_endpoints.sh

...

GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.713590 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.254655 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.222131 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.651065 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.989635 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.221113 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.649093 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.249565 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.162209 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.630144 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.214019 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.187007 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.705911 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.365181 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.132927 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000213420
http_code: 200
content_type: application/json
time_total: 0.596141 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.583007 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.615866 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.646784 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.164203 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.425747 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.632829 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.201664 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.142722 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.638697 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.160919 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.185793 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.641936 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.165889 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.135561 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.634513 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.178168 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.197299 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000157764
http_code: 200
content_type: application/json
time_total: 0.615373 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.593838 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.580416 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.810669 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.622353 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.383565 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.966226 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.159933 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.193736 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.790287 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.148597 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.365724 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.782608 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.438213 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.547309 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.794328 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.444436 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.386278 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
http_code: 200
content_type: application/json
time_total: 1.061237 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.776926 seconds


GET https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.721444 seconds


$ git st
On branch logstar/boxplot-title
Your branch is up to date with 'origin/logstar/boxplot-title'.

nothing to commit, working tree clean
```

</details>

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
- [NA] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have emojis in my PR and commits 😉

### CODE REVIEW

**Comment by afarrel** [comment]
Hi @logstar. Thank you for working on this module. Do the plots only use data from primary tumors or do they also contain data from relapsed tumors? If they contain data from relapsed/recurrent tumors then "Primary Tumor" may be misleading and should be renamed to simply Tumor and GTEx tissue gene expression.

**Comment by logstar** [comment]
> Hi @logstar. Thank you for working on this module. Do the plots only use data from primary tumors or do they also contain data from relapsed tumors? If they contain data from relapsed/recurrent tumors then "Primary Tumor" may be misleading and should be renamed to simply Tumor and GTEx tissue gene expression.

Thank you for the question. Only primary tumors are used to generate the plots.

<https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/f6c10f6df13d34ba4764d6bde29ceb1e30bd9806/db/build_tools/tpm_data_lists.R#L54-L69>

**Review by afarrel — APPROVED** [review]
Looks good @logstar . Thanks for getting the changes in and answering my question.

**Comment by logstar** [comment]
> Looks good @logstar . Thanks for getting the changes in and answering my question.

@afarrel - Thank you for reviewing. I will merge this PR soon.

**Pull request merged**
