### PR TITLE
📫Add all-cancer and all-GTEx-tissue plot and summary table endpoints

### LINKED ISSUE #44: Design and implement new endpoints for all-cancer and all-GTEx tissue bulk RNA-seq expression
Design and implement the following new endpoints for all-cancer and all-GTEx tissue bulk RNA-seq expression:

- `/tpm/gene-all-cancer-gtex/plot` endpoint transfers bulk RNA-seq TPM boxplots of all cancer groups and all GTEx tissue groups. If the boxplot is too wide, collapse GTEx tissue groups into one box, or use other approaches that will be proposed in #45 to make the boxplot narrower.
- `/tpm/gene-all-cancer-gtex/json` endpoint transfers bulk RNA-seq TPM summary statistics table of all cancer groups and all GTEx tissue groups.

cc @taylordm @chinwallaa @afarrel

### LINKED ISSUE #45: Improve readability of boxplots that have too many boxes
Boxplots transferred by `/tpm/gene-disease-gtex/plot` and `/tpm/gene-all-cancer/plot` are 13 inches wide and 9 inches long. Following is an example:

api_boxplot

When there are a couple of more boxes, the boxplot will become less readable, because smaller boxes and texts will be shown in the plot.

@taylordm suggested to collapse all GTEx tissue groups into one box. Implement this approach for the new endpoints in #44. The plots will be further discussed and evaluated.

cc @chinwallaa @afarrel @taylordm

### PR DESCRIPTION
**Pull request by logstar**
## Description

Added all-cancer and all-GTEx-tissue plot and summary table endpoints.

- Resolved #44 
- Resolved #45 

Note for reviewers: In the review, please only add comments or suggestions that are directly related code correctness or documentation readability.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changed

- Changed the interface of `get_gene_tpm_tbl` function by adding a required parameter `gtex_sample_group`.
- Changed the interface of `add_gene_tpm_box_group` function by adding an optional parameter `gtex_box_group`.
- Changed the behavior of `get_gene_tpm_boxplot_summary_tbl` function by allowing one sample group to have multiple unique `GTEx_tissue_subgroup`s and `GTEx_tissue_subgroup_UBERON`s.

### Added

- Added the following all-cancer and all-GTEx-tissue TPM boxplot and summary table endpoints:
  - `/tpm/gene-all-cancer-collapsed-gtex/plot` transfers boxplot with all GTEx tissues collapsed into one box.
  - `/tpm/gene-all-cancer-collapsed-gtex/json` transfers summary table with all GTEx tissues collapsed into one sample group.
  - `/tpm/gene-all-cancer-gtex/plot` transfers boxplot with each GTEx tissue subgroup as one box.
  - `/tpm/gene-all-cancer-gtex/json` transfers summary table with each GTEx tissue subgroup as one sample group.
- Added `curl` tests for the above all-cancer and all-GTEx-tissue TPM boxplot and summary table endpoints, in `tests/curl_test_endpoints.sh`.

## How Has This Been Tested?

- [x] Integration test

<details>
  <summary>**Terminal returns for testing DEV host. Click to expand.**</summary>

```text
$ git st
On branch acg
Your branch is up to date with 'origin/acg'.

nothing to commit, working tree clean

$ rm tests/http_response_output_files/png/*.png tests/http_response_output_files/json/*.json tests/results/*.tsv

$ ./tests/curl_test_endpoints.sh 

GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.258172 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.436654 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.420492 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.263910 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.310420 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.457913 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.267860 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.454943 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.447156 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.263423 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.541460 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.426151 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000213420&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.255761 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.429106 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000213420&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.455311 seconds


GET http://localhost:8082/tpm/gene-all-cancer/json?ensemblId=ENSG00000213420
http_code: 200
content_type: application/json
time_total: 0.225743 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.007589 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000213420&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 0.994899 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/json?ensemblId=ENSG00000213420
http_code: 200
content_type: application/json
time_total: 0.257944 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000213420&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.302714 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000213420&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.277916 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/json?ensemblId=ENSG00000213420
http_code: 200
content_type: application/json
time_total: 0.287717 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000213420&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.287103 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000213420&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.256290 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.267169 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.519475 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.398836 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.261575 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.453257 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.409980 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.260170 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.456813 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.441518 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.262513 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.472196 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.441619 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000157764&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.263992 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.567861 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000157764&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.387683 seconds


GET http://localhost:8082/tpm/gene-all-cancer/json?ensemblId=ENSG00000157764
http_code: 200
content_type: application/json
time_total: 0.235271 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 0.991376 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000157764&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 0.981801 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/json?ensemblId=ENSG00000157764
http_code: 200
content_type: application/json
time_total: 0.251346 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000157764&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.246673 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000157764&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.264880 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/json?ensemblId=ENSG00000157764
http_code: 200
content_type: application/json
time_total: 0.276227 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000157764&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.257954 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000157764&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.225313 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=EFO_0000621
http_code: 200
content_type: application/json
time_total: 0.376670 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.609124 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=EFO_0000621&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.594647 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=Orphanet_178
http_code: 200
content_type: application/json
time_total: 0.400856 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.493592 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=Orphanet_178&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.376393 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016718
http_code: 200
content_type: application/json
time_total: 0.367889 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.374106 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016718&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.568900 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016680
http_code: 200
content_type: application/json
time_total: 0.373818 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.567342 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016680&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.568448 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/json?ensemblId=ENSG00000273032&efoId=MONDO_0016685
http_code: 200
content_type: application/json
time_total: 0.375137 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.589693 seconds


GET http://localhost:8082/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000273032&efoId=MONDO_0016685&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.668127 seconds


GET http://localhost:8082/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
http_code: 200
content_type: application/json
time_total: 0.337727 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.097545 seconds


GET http://localhost:8082/tpm/gene-all-cancer/plot?ensemblId=ENSG00000273032&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.096425 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/json?ensemblId=ENSG00000273032
http_code: 200
content_type: application/json
time_total: 0.366653 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000273032&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 1.460458 seconds


GET http://localhost:8082/tpm/gene-all-cancer-collapsed-gtex/plot?ensemblId=ENSG00000273032&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 1.422966 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/json?ensemblId=ENSG00000273032
http_code: 200
content_type: application/json
time_total: 0.416603 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000273032&yAxisScale=linear
http_code: 200
content_type: image/png
time_total: 2.418889 seconds


GET http://localhost:8082/tpm/gene-all-cancer-gtex/plot?ensemblId=ENSG00000273032&yAxisScale=log10
http_code: 200
content_type: image/png
time_total: 2.402400 seconds


$ git st
On branch acg
Your branch is up to date with 'origin/acg'.

nothing to commit, working tree clean
```

</details>

For more details about local testing environment, options, and resources, see <https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/55afd9c5162e8c8304cecc351feb02be7170e379/README.md>.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
- [NA] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have emojis in my PR and commits 😉

cc @taylordm @chinwallaa

### CODE REVIEW

**Comment by logstar** [comment]
@chris-s-friedman @afarrel - Would you be able to review this PR before this Thursday? I will open a new PR probably on this Thursday, so the DEV site will be updated to the new PR.

**Review by afarrel — APPROVED** [review]
Thanks @logstar for your hard work on this.
I reviewed the code, the tables, and the plots. They look good.
Note: I did not rerun the code in my local environments.

**Comment by logstar** [comment]
@afarrel Thank you for reviewing. I will merge this pull request shortly.

**Comment by kelseykeith** [comment]
### Code and Results Review

Everything continues to look good as I move through the TPM PRs.

- Code is pulling from the correct version of the data (v10).
- Results from the API call match data in OpenPedCan-analysis tables.
- Plots have the correct boxplots for GTEx tissues, either none, collapsed into a single boxplot, or all tissues.
- Plots are the correct size for the number of boxplots they contain and have the correct titles.
- Tables also have the correct calculations for the correct grouping of GTEx tissues, either none, collapsed into a single boxplot, or all tissues.
- Changes to the database function correctly as far as I can tell and names were updated where appropriate.

**Pull request merged**
