### PR TITLE
Add relapse tumors samples to `/tpm/*` endpoint tables and plots

### LINKED ISSUE #51: Update TPM boxplots to show relapse tumors side-by-side with primary tumors
Currently, `/tpm/gene-disease-gtex` and `/tpm/gene-all-cancer` boxplots only show primary tumors.

As suggested by @taylordm , the TPM boxplots could be updated to show relapse tumors side-by-side with primary tumors. Primary tumors and relapse tumors could be plotted with different box colors, and a legend could be added in the boxplot to annotate different colors.

cc @taylordm @chinwallaa @afarrel

### LINKED ISSUE #54: Change boxplot box fill colors to be color blind friendly
Replace boxplot box fill colors from red to blue to be color blind friendly, as suggested by @taylordm .

Current box fill colors:

Screen Shot 2021-11-12 at 2 37 43 PM

Proposed replacement box fill colors:

Screen Shot 2021-11-12 at 2 41 15 PM

cc @chinwallaa @afarrel

### LINKED ISSUE #56: Change boxplot titles to describe primary/relapse of included tumor samples
Change boxplot titles to describe primary/relapse of included tumor samples, according to @taylordm's suggestion.

Currently, all titles use "Pediatric tumor" to describe tumor samples.

Following are the proposed changes of the "Pediatric tumor" to describe primary/relapse of included tumor samples.

- "Pediatric primary and relapse tumor" for boxplots with both primary and relapse tumor in the same box or different boxes.
- "Pediatric primary only tumor" for boxplots with only primary tumors.
- "Pediatric relapse only tumor" for boxplots with only relapse tumors.

cc @chinwallaa @afarrel

### LINKED ISSUE #57: Left align boxplot titles
Currently, all boxplot titles are centered. For large boxplots, PedOT website pages will probably render the leftmost part and allow horizontal scrolling. Therefore, titles of large boxplots may not be present or complete when rendered by PedOT website.

Align all boxplot titles to the left, to show full title in the first boxplot image view of PedOT website.

Centered title:

plot2

Left aligned title:

plotla3

cc @taylordm @chinwallaa

### LINKED ISSUE #58: Move boxplot color legend to left side
Currently, all boxplot legends are on the right side. For large boxplots, PedOT website pages will probably render the leftmost part and allow horizontal scrolling. Therefore, legend of large boxplots may not be present or complete when rendered by PedOT website.

Move all boxplot legends to top left, to show full legend in the first boxplot image view of PedOT website.

Legend on right side:

plotlr

Legend on top left side:

plotllt

cc @taylordm @chinwallaa

### PR DESCRIPTION
**Pull request by logstar**
## Description

Added relapse tumors samples to `/tpm/*` endpoint results and plots.

- Resolved #51 
- Resolved #54
- Resolved #56
- Resolved #57
- Resolved #58

Notes for reviewers:

- In the review, please only add comments or suggestions that are directly related code correctness or documentation readability.
- This PR is not broken into smaller PRs, because all changes in this PR are required to test whether the API works as expected or not. Most of the file changes are test results and plots.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Changed

- Changed the interfaces of the following endpoints by adding a required parameter `includeTumorDesc` to determine how independent primary and relapse tumor samples should be handled.
  - `/tpm/gene-disease-gtex/json`
  - `/tpm/gene-disease-gtex/plot`
  - `/tpm/gene-all-cancer/json`
  - `/tpm/gene-all-cancer/plot`
  - `/tpm/gene-all-cancer-collapsed-gtex/json`
  - `/tpm/gene-all-cancer-collapsed-gtex/plot`
  - `/tpm/gene-all-cancer-gtex/json`
  - `/tpm/gene-all-cancer-gtex/plot`
- Removed `tests/curl_test_endpoints.sh`.
- Changed the interface of `get_gene_tpm_tbl` function:
  - Changed `gtex_sample_group` parameter value choices to `"require"` and `"exclude"`.
  - Added a required parameter `relapse_sample_group`.
  - Removed `min_n_per_sample_group` parameter.
  - Added a column `specimen_descriptor` to returned table.
- Removed `src/add_gene_tpm_box_group.R`. The procedure in `add_gene_tpm_box_group` function is integrated into `get_gene_tpm_boxplot_tbl` function.
- Changed the interface of `get_gene_tpm_boxplot_tbl` function:
  - Added a required parameter `gtex_histology_group`.
  - Added a required parameter `spec_desc_group`.
  - Added a required parameter `min_n_per_box`.
  - Changed the returned table:
    - Renamed `x_labels` column to `x_label`.
    - Removed `box_group` column.
    - Added `histology_group` column.
    - Added `specimen_descriptor` column.
    - Added `specimen_descriptor_fill` column.
    - Added `specimen_descriptor_x_label` column.
    - Added `box_sample_count` column.
    - Added `x_label_sample_count` column.
- Changed the returned table of `tpm_boxplot_summary_tbl` function:
  - Added `specimen_descriptor_fill` column.
  - Added `box_sample_count` column.
- Renamed `src/ggplot2_publication_theme.R` to `src/ggplot2_boxplot_theme.R`.
- Moved `results/test-*.tsv` to `results/tsv/test-*.tsv`.
- Changed boxplot tumor box fill colors from red to blue, orange, and purple for primary, relapse, and primary-and-relapse tumor samples respectively.
- Changed boxplot titles to describe primary and relapse conditions of included tumor samples.
- Changed boxplot title alignment from centered to left-aligned.
- Changed boxplot legend location from right to top-left.
- Changed boxplot right margin and image width.
- Added legend to boxplot with two or more box colors.

### Added

- Added independent relapse tumor samples to OpenPedCan-api database `bulk_expression` schema and `bulk_expression_tpm_histology` table.
- Added `specimen_descriptor` column to OpenPedCan-api database `bulk_expression` schema and `bulk_expression_tpm_histology` table. The `specimen_descriptor` column describes whether a specimen is obtained from primary tumor, or relapse tumor, or normal tissue.
- Added `tests/run_tests.sh` to test API.
- Added `tests/r_test_scripts/test_endpoint_http.R` to test API HTTP server, which outputs `tests/results/endpoint_response_times.tsv` and `tests/plots/endpoint_response_time_boxplot.png` to summarize HTTP response times.
- Added `src/get_tpm_endpoint_tbl.R` to call `get_gene_tpm_tbl` and `get_gene_tpm_boxplot_tbl` with proper parameters according to HTTP request query parameters.

## How Has This Been Tested?

- [x] Integration test

**Task link/Screenshot/Terminal returns**:

```text
$ ./tests/run_tests.sh 
API base URL: http://localhost:8082
✔ |  OK F W S | Context
✔ | 288       | tests/r_test_scripts/test_endpoint_http.R [592.2 s]                                                                                                                                              

══ Results ═════════════
Duration: 592.3 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 288 ]
Done running run_tests.sh
```

For more details about local testing environment, options, and resources, see `README.md` of this PR branch.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
- [NA] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have emojis in my PR and commits 😉

cc @taylordm @chinwallaa

### CODE REVIEW

**Comment by afarrel** [comment]
Hi @logstar , I reviewed your code, tables, and plots. It looks good but before I approve I want to review the title names:
eg Pediatric primary and relapsed tumor and GTEx normal adult tissue gene expression. While this is fine, would a more succinct title be Pediatric Tumors and GTEx normal adult tissue gene expression (since you have the primary tumors, relapsed tumors, and normal tissue in the legend right below which can serve two purposes, legend and subtitle.)

What are your thoughts. I'm ready to approve pending this design decision. If the larger group wants the longer descriptive title that's fine.

**Comment by logstar** [comment]
> Hi @logstar , I reviewed your code, tables, and plots. It looks good but before I approve I want to review the title names: eg Pediatric primary and relapsed tumor and GTEx normal adult tissue gene expression. While this is fine, would a more succinct title be Pediatric Tumors and GTEx normal adult tissue gene expression (since you have the primary tumors, relapsed tumors, and normal tissue in the legend right below which can serve two purposes, legend and subtitle.)
> 
> What are your thoughts. I'm ready to approve pending this design decision. If the larger group wants the longer descriptive title that's fine.

@afarrel Thank you for reviewing. I think we could keep the longer title, to distinguish primary-and-relapse from primary-only and relapse-only. The title originally uses only "pediatric tumor", but changed to more descriptive ones, which was described in <https://github.com/PediatricOpenTargets/OpenPedCan-api/issues/56#issue-1056141024>.

**Review by afarrel — APPROVED** [review]
Hi @logstar , I reviewed your code, tables, and plots. It looks good. Thanks for your hard work on this.

**Comment by logstar** [comment]
> Hi @logstar , I reviewed your code, tables, and plots. It looks good. Thanks for your hard work on this.

Hi @afarrel . Thank you for reviewing. I will merge this PR after coordinating with @blackdenc . This PR requires a new database instance to be used for QA site, which needs to be configured by @blackdenc .

**Comment by kelseykeith** [comment]
### Code and Results Review

Everything continues to look good!

- API code runs correctly when I reconstruct the database and run the test server independently
- Code is pulling from the correct version of the data (v10).
- Results from the API call match data in OpenPedCan-analysis tables.
- Both tables and plots subset samples based on the cancer stage (`broad_tumor_descriptor`) appropriately.
- Plots have all the changes made in this PR
  - Correct combination of primary and relapse boxplots
  - New fill colors are color-blind friendly and correct for the combination of primary and relapse boxplots
  - Plot title text is correct and they are left-justified
  - Legends are top-left justified

**Pull request merged**
